### ISSUE TITLE
How to integrate WTForms/Flask-WTF with Flask-Classful

### ISSUE THREAD

**Issue by Destaq** [teracyhq/flask-classful#126]
I am trying to use the Flask-WTF library on top of Flask-Classful. Flask-WTF is used for submitting data and getting session information from forms with Flask.

In order to send this data, it needs to fire off a `POST` request. However, with `Flask-Classful`, you need to define every HTTP method in the FlaskView class. Is there any way to simply set up a blank method with flask-classful (i.e. emulating `@app.route("/login", methods=["GET", "POST"]`)?

In my case, I am trying to implement a simple login page. However, when I submit the information, I receive a 405 error stating that the method is not allowed.

```python
class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    email = StringField("Email Address", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])

    submit = SubmitField("Submit")

class LoginView(FlaskView):
    def index(self):
        form = LoginForm()
        if form.validate_on_submit():
            session["username"] = form.username.data
            session["email"] = form.email.data
            session["password"] = form.password.data

        return render_template("jinja/login.jinja", form=form)
```

Any way to overcome this?

**Comment by janmpeterka** [comment]
You just need to define method `post` instead of `index`. As both are predefined in Flask-Classful, they get its allowed methods (and I think `index` has `GET`).

here is working code from my app
```python
class LoginView(FlaskView):
    route_base = "/login"
    
    @route("")
    def show(self):
        form = create_form(LoginForm)
        return template("auth/login.html.j2", form=form)

    def post(self):
        form = LoginForm(request.form)
        if not form.validate_on_submit():
            save_form_to_session(request.form)
            return redirect(url_for("LoginView:show"))

        if do_login(username=form.username.data, password=form.password.data):
            return redirect(url_for("IndexView:index"))
        else:
            return redirect(url_for("LoginView:show"))
```

Few things here:
- you need two methods - one for showing login page, and another one for form submission. (you can use one allowing both methods and separating logic inside it, but I find it a messy solution).
- the `post` one needs to get data from `request.form`.
- in doing this, I ran into an issue with losing data if the form was not validated (as it just redirects). I solved it with helper methods `save_form_to_session` which well... saves form data to the session, and `create_form` which creates form and fills it with data from the session (if available). If you are interested, I can share the exact code for these helper methods. 
Another way to solve this is much simpler - you can render in the `post` method, but it seemed to me not DRY enough.
