### ISSUE TITLE
Should support route generation configuration for dashifying method names

### ISSUE THREAD

**Issue by j-walker23** [teracyhq/flask-classful#26]
Hey, thanks for taking this over. I love this lib.

Wondering if there is a way to change how the routes are generated from function names.
```
class TestView(FlaskView):
  def some_route(self):
    pass
```
The above will take `some_route` and turn it into `test/someroute`. In my stuff i moved to hyphens because some long names get hard to read. Is there a way to change it to `test/some-route`, other than a explicit `@route` decorator? Some kind of default config to always change underscores to hyphens.

**Comment by hoatle** [comment]
@j-walker23 thank you for your feedback, let me think more about this and will let you know more.

**Comment by j-walker23** [comment]
Thank you, I appreciate it!

**Comment by hoatle** [comment]
@j-walker23 I propose `method_dashified` attribute for class view or when registering the view with the app, like so:

```
class TestView(FlaskView):
  method_dashified = True

  def some_route(self):
    pass
```
or:

```
TestView.register(app, method_dashified=True)
```

then we can access `/test/some-route` instead of default `/test/some_route`.

I've sent a pull request for this, too: https://github.com/teracyhq/flask-classful/pull/28/files

Please let me know if this is good enough for your case.

**Comment by hoatle** [comment]
I'm going to merge and release v0.13.0 for this.

**Comment by hoatle** [comment]
done, closed.

**Comment by hoatle** [comment]
@j-walker23 v0.13.0 was released for this issue, enjoy!

**Comment by j-walker23** [comment]
This is awesome!! Sorry i didn't respond, forgot to check my notifications. Thanks for the update, very much appreciated.
