### ISSUE TITLE
add_url_rule() got multiple values for argument 'endpoint'

### ISSUE THREAD

**Issue by janscas** [teracyhq/flask-classful#91]
The docs clearly states that you can pass to register any additional params that add_url_rule can accept.
The problem is that if y pass `endpoint='home'` (a common param to add_url_rule) to the register function, then the following exception raises:

`add_url_rule() got multiple values for argument 'endpoint'`

That's because flask-classfull is not extracting from rule_options the posible user supplied values for the route_name (also known as 'endpoint').

Line 139 instead:
`route_name = cls.build_route_name(name)`

should be:
`route_name = rule_options.get('endpoint') or cls.build_route_name(name)`

or just simply change the register function signature to accept an endpoint parameter and then:
`route_name = endpoint or cls.build_route_name(name)`

**Comment by hoatle** [comment]
sorry, endpoint is not supported with the `register` method because the endpoint is generated for each class method instead of the view class.

you can see more here:
- http://flask-classful.teracy.org/#using-multiple-routes-for-a-single-view
- http://flask-classful.teracy.org/#specify-your-own-damn-endpoint you can specify your own endpoint with the `@route` decorator.
